export const SHARED_CONFIG = {
  PG_POOL_MAX: '10',
  PG_POOL_IDLE_TIMEOUT_MS: '30000',
  PG_POOL_CONNECTION_TIMEOUT_MS: '5000',
  PG_POOL_MAX_LIFETIME_SECONDS: '0',
  PG_POOL_ALLOW_EXIT_ON_IDLE: 'false'
};
