export const BOOLEAN_FIELDS = [
  'isDarkMode',
  'shouldIncludeYear',
  'shouldIncludeMonth',
  'shouldIncludeBusinessName',
  'quotesON',
  'invoiceSchedulesON',
  'smtpSecure',
  'reportsON',
  'styleProfilesON',
  'receiptPrintingOn',
  'invoiceSchedulesON',
  'presetsON',
  'isArchived',
  'labelUpperCase',
  'styleProfileLabelUpperCase',
  'showQuantity',
  'showUnit',
  'showRowNo',
  'ublON',
  'xrechnungON',
  'styleProfileShowQuantity',
  'styleProfileShowUnit',
  'styleProfileShowRowNo'
] as const;

export const DATE_FIELDS = [
  'appliedAt',
  'createdAt',
  'updatedAt',
  'attemptedAt',
  'issuedAt',
  'dueDate',
  'paidAt',
  'expiresAt',
  'startAt',
  'endAt',
  'nextRunAt',
  'lastRunAt',
  'dueAt',
  'startedAt',
  'completedAt'
] as const;
